// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestApi.Core.Infrastructure;

namespace TestApi.Core.Migrations
{
    [DbContext(typeof(TestApiDbContext))]
    [Migration("20200728153513_NewMigration")]
    partial class NewMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TestApi.Core.Domain.Card.Card", b =>
                {
                    b.Property<long>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.Property<int>("Suit")
                        .HasColumnType("int");

                    b.HasKey("Key");

                    b.HasAlternateKey("Suit", "Rank");

                    b.ToTable("Cards");

                    b.HasData(
                        new
                        {
                            Key = 1L,
                            Rank = 0,
                            Suit = 0
                        },
                        new
                        {
                            Key = 2L,
                            Rank = 1,
                            Suit = 0
                        },
                        new
                        {
                            Key = 3L,
                            Rank = 2,
                            Suit = 0
                        },
                        new
                        {
                            Key = 4L,
                            Rank = 3,
                            Suit = 0
                        },
                        new
                        {
                            Key = 5L,
                            Rank = 0,
                            Suit = 1
                        },
                        new
                        {
                            Key = 6L,
                            Rank = 1,
                            Suit = 1
                        },
                        new
                        {
                            Key = 7L,
                            Rank = 2,
                            Suit = 1
                        },
                        new
                        {
                            Key = 8L,
                            Rank = 3,
                            Suit = 1
                        },
                        new
                        {
                            Key = 9L,
                            Rank = 0,
                            Suit = 2
                        },
                        new
                        {
                            Key = 10L,
                            Rank = 1,
                            Suit = 2
                        },
                        new
                        {
                            Key = 11L,
                            Rank = 2,
                            Suit = 2
                        },
                        new
                        {
                            Key = 12L,
                            Rank = 3,
                            Suit = 2
                        },
                        new
                        {
                            Key = 13L,
                            Rank = 0,
                            Suit = 3
                        },
                        new
                        {
                            Key = 14L,
                            Rank = 1,
                            Suit = 3
                        },
                        new
                        {
                            Key = 15L,
                            Rank = 2,
                            Suit = 3
                        },
                        new
                        {
                            Key = 16L,
                            Rank = 3,
                            Suit = 3
                        },
                        new
                        {
                            Key = 17L,
                            Rank = 0,
                            Suit = 4
                        },
                        new
                        {
                            Key = 18L,
                            Rank = 1,
                            Suit = 4
                        },
                        new
                        {
                            Key = 19L,
                            Rank = 2,
                            Suit = 4
                        },
                        new
                        {
                            Key = 20L,
                            Rank = 3,
                            Suit = 4
                        },
                        new
                        {
                            Key = 21L,
                            Rank = 0,
                            Suit = 5
                        },
                        new
                        {
                            Key = 22L,
                            Rank = 1,
                            Suit = 5
                        },
                        new
                        {
                            Key = 23L,
                            Rank = 2,
                            Suit = 5
                        },
                        new
                        {
                            Key = 24L,
                            Rank = 3,
                            Suit = 5
                        },
                        new
                        {
                            Key = 25L,
                            Rank = 0,
                            Suit = 6
                        },
                        new
                        {
                            Key = 26L,
                            Rank = 1,
                            Suit = 6
                        },
                        new
                        {
                            Key = 27L,
                            Rank = 2,
                            Suit = 6
                        },
                        new
                        {
                            Key = 28L,
                            Rank = 3,
                            Suit = 6
                        },
                        new
                        {
                            Key = 29L,
                            Rank = 0,
                            Suit = 7
                        },
                        new
                        {
                            Key = 30L,
                            Rank = 1,
                            Suit = 7
                        },
                        new
                        {
                            Key = 31L,
                            Rank = 2,
                            Suit = 7
                        },
                        new
                        {
                            Key = 32L,
                            Rank = 3,
                            Suit = 7
                        },
                        new
                        {
                            Key = 33L,
                            Rank = 0,
                            Suit = 8
                        },
                        new
                        {
                            Key = 34L,
                            Rank = 1,
                            Suit = 8
                        },
                        new
                        {
                            Key = 35L,
                            Rank = 2,
                            Suit = 8
                        },
                        new
                        {
                            Key = 36L,
                            Rank = 3,
                            Suit = 8
                        },
                        new
                        {
                            Key = 37L,
                            Rank = 0,
                            Suit = 9
                        },
                        new
                        {
                            Key = 38L,
                            Rank = 1,
                            Suit = 9
                        },
                        new
                        {
                            Key = 39L,
                            Rank = 2,
                            Suit = 9
                        },
                        new
                        {
                            Key = 40L,
                            Rank = 3,
                            Suit = 9
                        },
                        new
                        {
                            Key = 41L,
                            Rank = 0,
                            Suit = 10
                        },
                        new
                        {
                            Key = 42L,
                            Rank = 1,
                            Suit = 10
                        },
                        new
                        {
                            Key = 43L,
                            Rank = 2,
                            Suit = 10
                        },
                        new
                        {
                            Key = 44L,
                            Rank = 3,
                            Suit = 10
                        },
                        new
                        {
                            Key = 45L,
                            Rank = 0,
                            Suit = 11
                        },
                        new
                        {
                            Key = 46L,
                            Rank = 1,
                            Suit = 11
                        },
                        new
                        {
                            Key = 47L,
                            Rank = 2,
                            Suit = 11
                        },
                        new
                        {
                            Key = 48L,
                            Rank = 3,
                            Suit = 11
                        },
                        new
                        {
                            Key = 49L,
                            Rank = 0,
                            Suit = 12
                        },
                        new
                        {
                            Key = 50L,
                            Rank = 1,
                            Suit = 12
                        },
                        new
                        {
                            Key = 51L,
                            Rank = 2,
                            Suit = 12
                        },
                        new
                        {
                            Key = 52L,
                            Rank = 3,
                            Suit = 12
                        },
                        new
                        {
                            Key = 53L,
                            Rank = 0,
                            Suit = 13
                        },
                        new
                        {
                            Key = 54L,
                            Rank = 1,
                            Suit = 13
                        },
                        new
                        {
                            Key = 55L,
                            Rank = 2,
                            Suit = 13
                        },
                        new
                        {
                            Key = 56L,
                            Rank = 3,
                            Suit = 13
                        });
                });

            modelBuilder.Entity("TestApi.Core.Domain.CardInDeck", b =>
                {
                    b.Property<long>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CardId")
                        .HasColumnName("CardId")
                        .HasColumnType("bigint");

                    b.Property<long>("DeckId")
                        .HasColumnName("DeckId")
                        .HasColumnType("bigint");

                    b.Property<int>("NumberInDeck")
                        .HasColumnType("int");

                    b.HasKey("Key");

                    b.HasIndex("CardId");

                    b.HasIndex("DeckId");

                    b.ToTable("CardInDecks");
                });

            modelBuilder.Entity("TestApi.Core.Domain.Deck.Deck", b =>
                {
                    b.Property<long>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Key");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL");

                    b.ToTable("Decks");
                });

            modelBuilder.Entity("TestApi.Core.Domain.CardInDeck", b =>
                {
                    b.HasOne("TestApi.Core.Domain.Card.Card", "Card")
                        .WithMany("CardInDecks")
                        .HasForeignKey("CardId")
                        .HasConstraintName("Card")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TestApi.Core.Domain.Deck.Deck", "Deck")
                        .WithMany("CardInDecks")
                        .HasForeignKey("DeckId")
                        .HasConstraintName("Deck")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
