// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestApi.Core.Infrastructure;

namespace TestApi.Core.Migrations
{
    [DbContext(typeof(TestApiDbContext))]
    partial class TestApiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TestApi.Core.Domain.Card.Card", b =>
                {
                    b.Property<long>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.Property<int>("Suit")
                        .HasColumnType("int");

                    b.HasKey("Key");

                    b.HasAlternateKey("Suit", "Rank");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("TestApi.Core.Domain.Deck.Deck", b =>
                {
                    b.Property<long>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("CardKey")
                        .HasColumnType("bigint");

                    b.HasKey("Key");

                    b.HasIndex("CardKey");

                    b.ToTable("Decks");
                });

            modelBuilder.Entity("TestApi.Core.Domain.Deck.Deck", b =>
                {
                    b.HasOne("TestApi.Core.Domain.Card.Card", null)
                        .WithMany("Decks")
                        .HasForeignKey("CardKey");
                });
#pragma warning restore 612, 618
        }
    }
}
