// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestApi.Core.Infrastructure;

namespace TestApi.Core.Migrations
{
    [DbContext(typeof(TestApiDbContext))]
    partial class TestApiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0-preview.7.20365.15");

            modelBuilder.Entity("TestApi.Core.Domain.Card.Card", b =>
                {
                    b.Property<long>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id")
                        .UseIdentityColumn();

                    b.HasKey("Key");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("TestApi.Core.Domain.Deck.Deck", b =>
                {
                    b.Property<long>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id")
                        .UseIdentityColumn();

                    b.Property<long?>("CardKey")
                        .HasColumnType("bigint");

                    b.HasKey("Key");

                    b.HasIndex("CardKey");

                    b.ToTable("Decks");
                });

            modelBuilder.Entity("TestApi.Core.Domain.Deck.Deck", b =>
                {
                    b.HasOne("TestApi.Core.Domain.Card.Card", null)
                        .WithMany("Decks")
                        .HasForeignKey("CardKey");
                });
#pragma warning restore 612, 618
        }
    }
}
